export const NOTIFICATION_TYPE = {
  BOOKING_CREATED: "BOOKING_CREATED",
  BOOKING_CONFIRMED: "BOOKING_CONFIRMED",
  BOOKING_UPDATED: "BOOKING_UPDATED",
  BOOKING_CANCELLED: "BOOKING_CANCELLED",
  BOOKING_REFUNDED: "BOOKING_REFUNDED",
  BOOKING_REFUND_INVITATION: "BOOKING_REFUND_INVITATION",
  BOOKING_REQUEST_CREATED: "BOOKING_REQUEST_CREATED",
  LESSON_UPCOMING: "LESSON_UPCOMING",
  CONTACT_REQUEST_CREATED: "CONTACT_REQUEST_CREATED",
  CALL_REQUEST_CREATED: "CALL_REQUEST_CREATED",
  PAYMENT_RECEIVED: "PAYMENT_RECEIVED",
  SYSTEM_ALERT: "SYSTEM_ALERT",
} as const;

export type NotificationType = (typeof NOTIFICATION_TYPE)[keyof typeof NOTIFICATION_TYPE];
