import type { AccountType } from "src/modules/accounts";
import type { AppRoute } from "src/types/router.types";
import {
  AdminDashboardPage,
  AdminReportsPage,
  AdminUsersPage,
  AdminStudentDetailsPage,
  AdminInstructorsPage,
  AdminBookingsPage,
  AdminArchivePage,
  AdminDrivingPage,
  AdminClassSchedulePage,
  AdminInboxRequestsPage,
  AdminRedirectContactRequestsToInbox,
  AdminRedirectBookedCallsToInbox,
  AdminRedirectTheoryPersonalRequestsToInbox,
  AdminPackagesPage,
  AdminCohortsPage,
  AdminBranchesPage,
  AdminCarsPage,
  AdminBlogsPage,
  AdminAccountsPage,
  AdminProfilePage,
  AdminNotificationsPage,
  AdminLearnHubPage,
  AdminExamQuestionsPage,
  AdminMarketingPage,
  AdminSettingsPage,
  AdminRedirectCohortsToLearn,
  AdminRedirectPackagesToLearn,
  AdminRedirectUsersToStudents,
  AdminRedirectUsersAnalyticsToStudents,
  AdminRedirectLegacyStudentsAnalytics,
  AdminRedirectLearnPracticalToStudents,
  AdminRedirectLearnTheoryToStudents,
  DirectorDashboardPage,
  DirectorCashPage,
  DirectorExpensesPage,
  DirectorRepairPage,
  DirectorFuelKmPage,
  DirectorInstructorHoursPage,
  DirectorDriverProfilePage,
  DirectorSalaryPage,
} from "src/pages/admin";
import { SUPER_ADMIN_ONLY_ACCOUNT_TYPES } from "./admin.consts";

const STAFF: readonly AccountType[] = ["super_admin", "admin"];

export const adminRoutes: readonly AppRoute[] = [
  { path: "/admin/dashboard", component: AdminDashboardPage, allowedAccountTypes: STAFF },
  { path: "/admin/reports", component: AdminReportsPage, allowedAccountTypes: STAFF },
  { path: "/admin/branches", component: AdminBranchesPage, allowedAccountTypes: STAFF },
  { path: "/admin/cars", component: AdminCarsPage, allowedAccountTypes: SUPER_ADMIN_ONLY_ACCOUNT_TYPES },
  { path: "/admin/students/analytics", component: AdminRedirectLegacyStudentsAnalytics, allowedAccountTypes: STAFF },
  { path: "/admin/students/:id", component: AdminStudentDetailsPage, allowedAccountTypes: STAFF },
  { path: "/admin/students", component: AdminUsersPage, allowedAccountTypes: STAFF },
  { path: "/admin/users/analytics", component: AdminRedirectUsersAnalyticsToStudents, allowedAccountTypes: STAFF },
  { path: "/admin/users", component: AdminRedirectUsersToStudents, allowedAccountTypes: STAFF },
  { path: "/admin/learn/practical", component: AdminRedirectLearnPracticalToStudents, allowedAccountTypes: STAFF },
  { path: "/admin/learn/theory", component: AdminRedirectLearnTheoryToStudents, allowedAccountTypes: STAFF },
  { path: "/admin/instructors", component: AdminInstructorsPage, allowedAccountTypes: STAFF },
  { path: "/admin/bookings/debts", component: AdminBookingsPage, allowedAccountTypes: STAFF },
  { path: "/admin/bookings", component: AdminBookingsPage, allowedAccountTypes: STAFF },
  { path: "/admin/archive", component: AdminArchivePage, allowedAccountTypes: STAFF },
  { path: "/admin/driving", component: AdminDrivingPage, allowedAccountTypes: STAFF },
  { path: "/admin/settings", component: AdminSettingsPage, allowedAccountTypes: STAFF },
  { path: "/admin/class-schedule", component: AdminClassSchedulePage, allowedAccountTypes: STAFF },
  { path: "/admin/notifications", component: AdminNotificationsPage, allowedAccountTypes: STAFF },
  { path: "/admin/inbox/theory-personal", component: AdminInboxRequestsPage, allowedAccountTypes: STAFF },
  { path: "/admin/inbox/booked-calls", component: AdminInboxRequestsPage, allowedAccountTypes: STAFF },
  { path: "/admin/inbox/contact-requests", component: AdminInboxRequestsPage, allowedAccountTypes: STAFF },
  { path: "/admin/inbox/gift-bookings", component: AdminInboxRequestsPage, allowedAccountTypes: STAFF },
  { path: "/admin/inbox", component: AdminInboxRequestsPage, allowedAccountTypes: STAFF },
  { path: "/admin/contact-requests", component: AdminRedirectContactRequestsToInbox, allowedAccountTypes: STAFF },
  { path: "/admin/booked-calls", component: AdminRedirectBookedCallsToInbox, allowedAccountTypes: STAFF },
  { path: "/admin/theory-personal-requests", component: AdminRedirectTheoryPersonalRequestsToInbox, allowedAccountTypes: STAFF },
  { path: "/admin/learn/exam-questions", component: AdminExamQuestionsPage, allowedAccountTypes: STAFF },
  { path: "/admin/learn/groups", component: AdminCohortsPage, allowedAccountTypes: STAFF },
  { path: "/admin/learn/packages", component: AdminPackagesPage, allowedAccountTypes: STAFF },
  { path: "/admin/learn", component: AdminLearnHubPage, allowedAccountTypes: STAFF },
  { path: "/admin/packages", component: AdminRedirectPackagesToLearn, allowedAccountTypes: STAFF },
  { path: "/admin/cohorts", component: AdminRedirectCohortsToLearn, allowedAccountTypes: STAFF },
  { path: "/admin/blogs", component: AdminBlogsPage, allowedAccountTypes: SUPER_ADMIN_ONLY_ACCOUNT_TYPES },
  { path: "/admin/marketing-content", component: AdminMarketingPage, allowedAccountTypes: SUPER_ADMIN_ONLY_ACCOUNT_TYPES },
  { path: "/admin/director/cash", component: DirectorCashPage, allowedAccountTypes: SUPER_ADMIN_ONLY_ACCOUNT_TYPES },
  { path: "/admin/director/expenses", component: DirectorExpensesPage, allowedAccountTypes: SUPER_ADMIN_ONLY_ACCOUNT_TYPES },
  { path: "/admin/director/repair", component: DirectorRepairPage, allowedAccountTypes: SUPER_ADMIN_ONLY_ACCOUNT_TYPES },
  { path: "/admin/director/fuel-km", component: DirectorFuelKmPage, allowedAccountTypes: SUPER_ADMIN_ONLY_ACCOUNT_TYPES },
  { path: "/admin/director/instructor-hours", component: DirectorInstructorHoursPage, allowedAccountTypes: SUPER_ADMIN_ONLY_ACCOUNT_TYPES },
  { path: "/admin/director/driver-profile", component: DirectorDriverProfilePage, allowedAccountTypes: SUPER_ADMIN_ONLY_ACCOUNT_TYPES },
  { path: "/admin/director/salary", component: DirectorSalaryPage, allowedAccountTypes: SUPER_ADMIN_ONLY_ACCOUNT_TYPES },
  { path: "/admin/director", component: DirectorDashboardPage, allowedAccountTypes: SUPER_ADMIN_ONLY_ACCOUNT_TYPES },
  { path: "/admin/accounts", component: AdminAccountsPage, allowedAccountTypes: SUPER_ADMIN_ONLY_ACCOUNT_TYPES },
  { path: "/admin/profile", component: AdminProfilePage, allowedAccountTypes: STAFF },
];
