import type { AppRoute } from "src/shared/types/router.types";
import {
  AdminDashboardPage,
  AdminUsersPage,
  AdminInstructorsPage,
  AdminBookingsPage,
  AdminPackagesPage,
  AdminCohortsPage,
  AdminBranchesPage,
  AdminCarsPage,
  AdminBlogsPage,
  AdminAccountsPage,
  AdminFinancePage,
  AdminProfilePage,
  AdminLearnHubPage,
  AdminLearnPracticalPage,
  AdminLearnTheoryPage,
  AdminRedirectCohortsToLearn,
  AdminRedirectPackagesToLearn,
} from "src/pages/admin";

export const adminRoutes: readonly AppRoute[] = [
  { path: "/admin/dashboard", component: AdminDashboardPage },
  { path: "/admin/branches", component: AdminBranchesPage },
  { path: "/admin/cars", component: AdminCarsPage },
  { path: "/admin/users", component: AdminUsersPage },
  { path: "/admin/instructors", component: AdminInstructorsPage },
  { path: "/admin/bookings", component: AdminBookingsPage },
  { path: "/admin/learn/practical", component: AdminLearnPracticalPage },
  { path: "/admin/learn/theory", component: AdminLearnTheoryPage },
  { path: "/admin/learn/groups", component: AdminCohortsPage },
  { path: "/admin/learn/packages", component: AdminPackagesPage },
  { path: "/admin/learn", component: AdminLearnHubPage },
  { path: "/admin/packages", component: AdminRedirectPackagesToLearn },
  { path: "/admin/cohorts", component: AdminRedirectCohortsToLearn },
  { path: "/admin/blogs", component: AdminBlogsPage },
  { path: "/admin/finance", component: AdminFinancePage },
  { path: "/admin/accounts", component: AdminAccountsPage },
  { path: "/admin/profile", component: AdminProfilePage },
];
