import type { Metadata } from "next";
import { cookies, headers } from "next/headers";
import { LEGAL_DOCS } from "src/lib/legalDocsContent";
import { absoluteUrl, siteUrl } from "./site";

export type SeoLang = "en" | "ru" | "am";

type LocalizedText = Record<SeoLang, string>;

type RouteSeo = {
  title: LocalizedText;
  description: LocalizedText;
  keywords: LocalizedText;
};

const BRAND_TITLE: LocalizedText = {
  en: "Viva Autoschool",
  ru: "Автошкола Viva",
  am: "Վիվա Ավտոդպրոց",
};

/** Full homepage titles (absolute — already include the brand). */
const HOME_TITLE: LocalizedText = {
  en: "Viva Autoschool Yerevan | Driving Lessons & Theory in Armenia",
  ru: "Автошкола Viva Ереван | Уроки вождения и теория в Армении",
  am: "Վիվա Ավտոդպրոց Երևան | Վարորդական դասեր և տեսություն Հայաստանում",
};

const DEFAULT_DESCRIPTION: LocalizedText = {
  en: "Driving school in Yerevan, Armenia. Certified instructors, practical lessons, theory courses, and license exam preparation at Viva Autoschool.",
  ru: "Автошкола в Ереване, Армения. Сертифицированные инструкторы, практика, теория и подготовка к экзамену на права в автошколе Viva.",
  am: "Ավտոդպրոց Երևանում, Հայաստան։ Սերտիֆիկացված հրահանգիչներ, պրակտիկ դասեր, տեսություն և վարորդական քննության պատրաստում «Վիվա Ավտոդպրոցում»։",
};

const DEFAULT_KEYWORDS: LocalizedText = {
  en: "driving school Yerevan, driving school Armenia, Viva Autoschool, driving lessons Yerevan, theory exam preparation, driving instructor Armenia, driver's license Armenia",
  ru: "автошкола Ереван, автошкола Армения, автошкола Viva, уроки вождения Ереван, подготовка к теоретическому экзамену, инструктор по вождению, водительские права Армения",
  am: "ավտոդպրոց Երևան, ավտոդպրոց Հայաստան, Վիվա Ավտոդպրոց, վարորդական դասեր Երևան, տեսական քննության պատրաստում, վարորդական հրահանգիչ, վարորդական իրավունք Հայաստան",
};

/** Default social share image (generated by `app/opengraph-image.tsx`). */
export const DEFAULT_OG_IMAGE = "/opengraph-image";

const ROUTE_SEO: Record<string, RouteSeo> = {
  "/": {
    title: HOME_TITLE,
    description: {
      en: "Learn to drive in Yerevan with Viva Autoschool — certified instructors, practical lessons, theory courses, and Armenian driver's license exam prep.",
      ru: "Научитесь водить в Ереване в автошколе Viva — сертифицированные инструкторы, практика, теория и подготовка к экзамену на права в Армении.",
      am: "Սովորեք վարել Երևանում «Վիվա Ավտոդպրոցում»՝ սերտիֆիկացված հրահանգիչներ, պրակտիկա, տեսություն և վարորդական իրավունքի քննության պատրաստում։",
    },
    keywords: {
      en: "driving school Yerevan, Viva Autoschool, driving lessons Armenia, license preparation, theory courses",
      ru: "автошкола Ереван, автошкола Viva, уроки вождения Армения, подготовка к правам, курсы теории",
      am: "ավտոդպրոց Երևան, Վիվա Ավտոդպրոց, վարորդական դասեր Հայաստան, վարորդական իրավունքի պատրաստում, տեսության դասընթաց",
    },
  },
  "/services": {
    title: { en: "Services", ru: "Услуги", am: "Ծառայություններ" },
    description: {
      en: "Practical driving lessons, theory courses, license preparation, and refresher training — everything you need for your Armenian driver's license.",
      ru: "Практические уроки вождения, теория, подготовка к экзамену и восстановление навыков — все для получения прав в Армении.",
      am: "Պրակտիկ վարորդական դասեր, տեսական ուսուցում, քննության պատրաստում և հմտությունների վերապատրաստում՝ վարորդական իրավունքի համար Հայաստանում։",
    },
    keywords: {
      en: "driving services Armenia, practical driving lessons Yerevan, theory courses",
      ru: "услуги автошколы Армения, практические уроки вождения Ереван, курсы теории",
      am: "ավտոդպրոցի ծառայություններ Հայաստան, պրակտիկ վարորդական դասեր Երևան, տեսության դասընթացներ",
    },
  },
  "/about": {
    title: { en: "About Us", ru: "О нас", am: "Մեր մասին" },
    description: {
      en: "About Viva Autoschool — a trusted driving school in Yerevan, Armenia. Certified instructors, modern vehicles, and student-centered training.",
      ru: "Об автошколе Viva — надёжная автошкола в Ереване, Армения. Сертифицированные инструкторы и современные автомобили.",
      am: "«Վիվա Ավտոդպրոցի» մասին՝ վստահելի ավտոդպրոց Երևանում, Հայաստան։ Սերտիֆիկացված հրահանգիչներ և ժամանակակից մեքենաներ։",
    },
    keywords: {
      en: "about Viva Autoschool, driving school Yerevan history",
      ru: "о автошколе Viva, история автошколы Ереван",
      am: "Վիվա Ավտոդպրոցի մասին, ավտոդպրոց Երևան",
    },
  },
  "/packages": {
    title: {
      en: "Packages & Pricing",
      ru: "Пакеты и цены",
      am: "Փաթեթներ և գներ",
    },
    description: {
      en: "Compare driving lesson packages at Viva Autoschool in Yerevan — flexible options for practical training and theory.",
      ru: "Сравните пакеты уроков вождения в автошколе Viva в Ереване — гибкие варианты практики и теории.",
      am: "Համեմատեք «Վիվա Ավտոդպրոցի» վարորդական դասերի փաթեթները Երևանում՝ ճկուն տարբերակներով և ներառված տեսությամբ։",
    },
    keywords: {
      en: "driving lesson packages Yerevan, autoschool pricing Armenia",
      ru: "пакеты уроков вождения Ереван, цены автошколы Армения",
      am: "վարորդական դասերի փաթեթներ Երևան, ավտոդպրոցի գներ Հայաստան",
    },
  },
  "/instructors": {
    title: { en: "Instructors", ru: "Инструкторы", am: "Հրահանգիչներ" },
    description: {
      en: "Meet certified driving instructors at Viva Autoschool in Yerevan — patient, professional, and focused on safe drivers.",
      ru: "Познакомьтесь с сертифицированными инструкторами автошколы Viva в Ереване — терпеливыми и профессиональными.",
      am: "Ծանոթացեք «Վիվա Ավտոդպրոցի» սերտիֆիկացված վարորդական հրահանգիչներին Երևանում՝ համբերատար և պրոֆեսիոնալ թիմ։",
    },
    keywords: {
      en: "driving instructors Yerevan, certified instructor Armenia, Viva Autoschool",
      ru: "инструкторы по вождению Ереван, сертифицированный инструктор Армения, автошкола Viva",
      am: "վարորդական հրահանգիչներ Երևան, սերտիֆիկացված հրահանգիչ Հայաստան, Վիվա Ավտոդպրոց",
    },
  },
  "/contact": {
    title: { en: "Contact", ru: "Контакты", am: "Կապ" },
    description: {
      en: "Contact Viva Autoschool in Yerevan — phone, email, branches, and driving lesson booking.",
      ru: "Свяжитесь с автошколой Viva в Ереване — телефон, email, филиалы и запись на уроки.",
      am: "Կապ հաստատեք «Վիվա Ավտոդպրոցի» հետ Երևանում՝ հեռախոս, էլ․փոստ, մասնաճյուղեր և դասերի ամրագրում։",
    },
    keywords: {
      en: "contact Viva Autoschool, driving school branches Yerevan",
      ru: "контакты автошколы Viva, филиалы автошколы Ереван",
      am: "Վիվա Ավտոդպրոց կոնտակտներ, ավտոդպրոցի մասնաճյուղեր Երևան",
    },
  },
  "/blogs": {
    title: { en: "Blog", ru: "Блог", am: "Բլոգ" },
    description: {
      en: "Driving tips, theory exam preparation, and news from Viva Autoschool in Yerevan.",
      ru: "Советы по вождению, подготовка к теории и новости автошколы Viva в Ереване.",
      am: "Վարելու խորհուրդներ, տեսական քննության պատրաստում և «Վիվա Ավտոդպրոցի» նորություններ Երևանից։",
    },
    keywords: {
      en: "driving blog Armenia, theory test tips Yerevan",
      ru: "блог о вождении Армения, советы к теоретическому экзамену Ереван",
      am: "վարորդական բլոգ Հայաստան, տեսական քննության խորհուրդներ Երևան",
    },
  },
  "/exam-tests": {
    title: {
      en: "Exam Tests",
      ru: "Экзаменационные тесты",
      am: "Քննության թեստեր",
    },
    description: {
      en: "Free driving theory exam practice for Armenia — thematic questions and exam-style tests from Viva Autoschool.",
      ru: "Бесплатная практика к экзамену по теории вождения в Армении — тематические вопросы и тесты от автошколы Viva.",
      am: "Անվճար վարորդական տեսական քննության պրակտիկա Հայաստանում՝ թեմատիկ հարցեր և քննության թեստեր «Վիվա Ավտոդպրոցից»։",
    },
    keywords: {
      en: "driving theory tests Armenia, exam practice questions Yerevan",
      ru: "тесты по теории вождения Армения, вопросы для практики экзамена Ереван",
      am: "վարորդական տեսության թեստեր Հայաստան, քննության պրակտիկ հարցեր Երևան",
    },
  },
  "/road-signs": {
    title: {
      en: "Road Signs",
      ru: "Дорожные знаки",
      am: "Ճանապարհային նշաններ",
    },
    description: {
      en: "Learn Armenian road signs by category and practice with image-based quizzes at Viva Autoschool.",
      ru: "Изучайте дорожные знаки Армении по категориям и практикуйтесь с тестами по картинкам в автошколе Viva.",
      am: "Ուսուցեք հայկական ճանապարհային նշանները ըստ խմբերի և պրակտիկա անցեք պատկերներով թեստերով «Վիվա Ավտոդպրոցում»։",
    },
    keywords: {
      en: "Armenia road signs, driving theory signs practice, Yerevan",
      ru: "дорожные знаки Армения, практика знаков теории вождения, Ереван",
      am: "ճանապարհային նշաններ Հայաստան, վարորդական տեսության նշանների պրակտիկա, Երևան",
    },
  },
  "/thematic-questions": {
    title: {
      en: "Exam Tests & Topic Practice",
      ru: "Тесты и практика по темам",
      am: "Թեստեր և թեմատիկ պրակտիկա",
    },
    description: {
      en: "Practice thematic driving theory questions and prepare for the official Armenian exam with Viva Autoschool.",
      ru: "Практикуйте тематические вопросы по теории и готовьтесь к официальному экзамену в Армении с автошколой Viva.",
      am: "Վարժվեք տեսական թեմատիկ հարցերով և պատրաստվեք պաշտոնական քննությանը Հայաստանում «Վիվա Ավտոդպրոցի» հետ։",
    },
    keywords: {
      en: "thematic driving questions Armenia, theory topic practice Yerevan",
      ru: "тематические вопросы по вождению Армения, практика тем по теории Ереван",
      am: "տեսական թեմատիկ հարցեր Հայաստան, վարորդական թեմատիկ պրակտիկա Երևան",
    },
  },
};

function normalizeSeoLang(value: string | null | undefined): SeoLang | null {
  if (!value) return null;
  const normalized = value.toLowerCase();
  if (normalized === "en" || normalized.startsWith("en-")) return "en";
  if (normalized === "ru" || normalized.startsWith("ru-")) return "ru";
  if (normalized === "am" || normalized.startsWith("am-") || normalized === "hy" || normalized.startsWith("hy-")) {
    return "am";
  }
  return null;
}

/** BCP 47 / HTML `lang` value (Armenian is `hy`, not `am`). */
export function htmlLangFromSeoLang(lang: SeoLang): string {
  if (lang === "am") return "hy";
  return lang;
}

export function ogLocaleFromSeoLang(lang: SeoLang): string {
  if (lang === "am") return "hy_AM";
  if (lang === "ru") return "ru_RU";
  return "en_US";
}

export async function getRequestSeoLang(): Promise<SeoLang> {
  const cookieStore = await cookies();
  const langFromCookie = normalizeSeoLang(cookieStore.get("viva_lang")?.value);
  if (langFromCookie) return langFromCookie;

  const headerStore = await headers();
  const langFromHeader = normalizeSeoLang(headerStore.get("accept-language"));
  return langFromHeader ?? "am";
}

export function getRouteSeo(pathname: string, lang: SeoLang): { title: string; description: string; keywords: string } {
  const routeSeo = ROUTE_SEO[pathname];
  if (!routeSeo) {
    return {
      title: BRAND_TITLE[lang],
      description: DEFAULT_DESCRIPTION[lang],
      keywords: DEFAULT_KEYWORDS[lang],
    };
  }
  return {
    title: routeSeo.title[lang],
    description: routeSeo.description[lang],
    keywords: routeSeo.keywords[lang],
  };
}

function defaultOgImages(): NonNullable<Metadata["openGraph"]>["images"] {
  return [
    {
      url: DEFAULT_OG_IMAGE,
      width: 1200,
      height: 630,
      alt: BRAND_TITLE.am,
    },
  ];
}

export function buildRouteMetadata(pathname: string, lang: SeoLang): Metadata {
  const seo = getRouteSeo(pathname, lang);
  const canonical = pathname === "/" ? "/" : pathname;
  const isHome = pathname === "/";
  const ogTitle = isHome ? seo.title : `${seo.title} | ${BRAND_TITLE[lang]}`;

  return {
    title: isHome ? { absolute: seo.title } : seo.title,
    description: seo.description,
    keywords: seo.keywords,
    alternates: { canonical },
    openGraph: {
      type: "website",
      siteName: BRAND_TITLE[lang],
      title: ogTitle,
      description: seo.description,
      url: canonical,
      locale: ogLocaleFromSeoLang(lang),
      images: defaultOgImages(),
    },
    twitter: {
      card: "summary_large_image",
      title: ogTitle,
      description: seo.description,
      images: [DEFAULT_OG_IMAGE],
    },
  };
}

export function legalMetadata(kind: "privacy" | "terms" | "payments", lang: SeoLang, pathname: string): Metadata {
  const doc = LEGAL_DOCS[kind][lang];
  const base = buildRouteMetadata(pathname, lang);
  return {
    ...base,
    title: doc.pageTitle,
    description: doc.metaDescription,
    openGraph: {
      ...(base.openGraph ?? {}),
      title: doc.pageTitle,
      description: doc.metaDescription,
    },
    twitter: {
      ...(base.twitter ?? {}),
      title: doc.pageTitle,
      description: doc.metaDescription,
    },
  };
}

export function baseLayoutMetadata(lang: SeoLang): Metadata {
  return {
    metadataBase: siteUrl(),
    icons: {
      icon: [{ url: "/favicon.png", type: "image/png" }],
      shortcut: ["/favicon.png"],
      apple: ["/favicon.png"],
    },
    title: {
      default: BRAND_TITLE[lang],
      template: `%s | ${BRAND_TITLE[lang]}`,
    },
    description: DEFAULT_DESCRIPTION[lang],
    keywords: DEFAULT_KEYWORDS[lang],
    applicationName: BRAND_TITLE[lang],
    authors: [{ name: BRAND_TITLE[lang], url: absoluteUrl("/") }],
    creator: BRAND_TITLE[lang],
    publisher: BRAND_TITLE[lang],
    category: "education",
    alternates: { canonical: "/" },
    openGraph: {
      type: "website",
      siteName: BRAND_TITLE[lang],
      title: HOME_TITLE[lang],
      description: DEFAULT_DESCRIPTION[lang],
      locale: ogLocaleFromSeoLang(lang),
      url: "/",
      images: defaultOgImages(),
    },
    twitter: {
      card: "summary_large_image",
      title: HOME_TITLE[lang],
      description: DEFAULT_DESCRIPTION[lang],
      images: [DEFAULT_OG_IMAGE],
    },
    robots: {
      index: true,
      follow: true,
      googleBot: {
        index: true,
        follow: true,
        "max-snippet": -1,
        "max-image-preview": "large",
        "max-video-preview": -1,
      },
    },
  };
}

export { BRAND_TITLE, DEFAULT_DESCRIPTION, HOME_TITLE };
