export { default as DashboardPage } from "./Dashboard";
export { default as DashboardLearnPage } from "./DashboardLearn";
export { default as DashboardExamTestsPage } from "./DashboardExamTests";
export { default as DashboardExamQuizPage } from "./DashboardExamQuiz";
export { default as DashboardThematicTestsPage } from "./DashboardThematicTests";
export { default as DashboardBookingsPage } from "./DashboardBookingsOutlet";
export { DashboardBookingsListTab } from "./DashboardBookings";
export { DashboardBookingsPackageTab } from "./DashboardBookingsPackage";
export { DashboardBookingsPracticalTab } from "./DashboardBookingsPractical";
export { default as DashboardPaymentsPage } from "./DashboardPayments";
export { default as DashboardProfilePage } from "./DashboardProfile";
export { default as DashboardServicesPage } from "./DashboardServices";
export { default as DashboardLessonsPage } from "./DashboardLessons";
export { default as DashboardProgressPage } from "./DashboardProgress";
